services:
  - type: web
    name: holify-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: holify-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: holify-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: holify-db
          property: password
      - key: JWT_SECRET
        value: "your-super-secret"

databases:
  - name: holify-db
    plan: free
